export const ProfessionalFieldsAndAreasOfExpertise152 = [
  "Government Affairs (Lobbying)",
  "Government Affairs (Non-Lobbying)",
  "Business Development",
  "Sales and Capture Strategies",
  "Marketing and Promotion",
  "Public Relations",
  "Advisory Services",
  "Crisis Communications and Reputation Management",
  "Trade Show Management",
  "Government Contracting, Procurement, and Compliance",
  "Contract Management",
  "Financial Contracting",
  "Procurement and Sourcing",
  "Military Procurement and Acquisition",
  "Federal Budgeting and Appropriations",
  "Government Proposal Writing (RFP, RFQ, RFI)",
  "Small Business Set-Asides (8(a), SDVOSB, HUBZone)",
  "GSA Schedule Management",
  "Defense Industrial Base Compliance (CMMC, ITAR, DFARS)",
  "Export Compliance Regulations",
  "International Trade Regulations",
  "Government Grant and Cooperative Agreement Compliance",
  "Risk Management, Security, and Regulatory Compliance",
  "Risk Management",
  "Compliance Management",
  "Legal and Regulatory Services",
  "Ethics and Anti-Corruption Compliance",
  "Facility Security Clearances (FCL) and Personnel Vetting",
  "Classified Information Handling and Security Protocols",
  "Supply Chain Security and Resilience",
  "Insider Threat Detection and Mitigation",
  "Fraud Detection and Prevention",
  "Cybersecurity and Information Technology",
  "Cyber Security",
  "Zero Trust Architecture Implementation",
  "SCADA and Industrial Control Systems (ICS) Security",
  "Cyber Forensic Analysis",
  "Cyber Defense Operations",
  "Cyber Threat Intelligence and Analysis",
  "Supply Chain Cybersecurity Risk Management",
  "Penetration Testing and Red Teaming",
  "Cloud Security and FedRAMP Compliance",
  "Mobile Device and Endpoint Security",
  "Cyber Resilience and Incident Response Planning",
  "Biometric and Identity Management Security",
  "IT Support Services",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning and Artificial Intelligence",
  "Blockchain and Distributed Ledger Technologies",
  "Cloud Computing Services",
  "Internet of Things (IoT) Integration",
  "Quantum Computing Research",
  "Engineering, Development, and Emerging Technologies",
  "Engineering",
  "Systems Architecture",
  "Development Operations (DevOps)",
  "Software Development",
  "Aerospace Defense Systems",
  "Unmanned Aerial Systems Operations",
  "Weapon Systems Lifecycle Management",
  "AI and Autonomous Systems Policy and Implementation",
  "Space Policy and Commercial Space Operations",
  "Defense, Intelligence, and Security Operations",
  "Military Intelligence Analysis",
  "Counterintelligence Measures",
  "Counterterrorism Strategies",
  "Signals Intelligence (SIGINT) Operations",
  "Intelligence Analysis",
  "Operations Management",
  "Joint Operations Planning",
  "Domestic Security Measures",
  "Internal Security Operations",
  "Border Management",
  "Maritime Operations and Strategy",
  "International Security Operations",
  "Military Logistics Management",
  "Special Operations Tactics",
  "Combat Engineering",
  "Defense Readiness and Training",
  "International Affairs, Diplomacy, and Foreign Relations",
  "Diplomacy and Foreign Service",
  "International Partnerships Development",
  "Foreign Military Sales Management",
  "Deemed Export Compliance and Licensing",
  "Customs and Trade Compliance",
  "International Agreements Coordination",
  "Consular Services Management",
  "Public Health, Medical, and Environmental Policy",
  "Public Health Initiatives",
  "Healthcare Administration",
  "Mental Health Services",
  "Epidemiology and Disease Control",
  "Health Policy and Legislation",
  "Community Health Outreach",
  "Public Health Emergency Preparedness and Response (HHS, CDC, NIH)",
  "Regenerative Medicine and Advanced Biologics Policy Consulting",
  "Clinical Trial Management and Regulatory Compliance (NIH, FDA)",
  "Biomedical Research and Translational Science Support (NIH, BARDA)",
  "Biotechnology Regulations and Compliance (NIH, FDA, USDA)",
  "Agriculture, Food Safety, and Energy Policy",
  "Agricultural Policy and Rural Development Consulting (USDA)",
  "Food Safety and Inspection Compliance (USDA, FDA)",
  "Nutrition Assistance Program Administration (USDA, SNAP, WIC)",
  "Energy Security and Resilience (Microgrids, Renewables, etc.)",
  "Environmental Policy Development",
  "Climate Policy and Analysis",
  "Research, Development, and Innovation Support",
  "Research and Development",
  "Technology Transfer Processes",
  "Federal Research Funding Strategies (SBIR, STTR, NIH, NSF, DOE, DOD, NASA)",
  "Technology Commercialization and Tech Transfer for SBIR/STTR Projects",
  "Standards Development",
  "Measurement Science",
  "Quality Assurance Processes",
  "Training, Workforce Development, and Strategic Planning",
  "Training and Development",
  "Workforce Development and Talent Pipeline Strategies",
  "Strategic Planning",
  "Change Management Processes",
  "Public-Private Partnerships (PPP) Development",
  "Humanitarian Assistance and Disaster Relief Coordination",
  "Logistics, Operations, and Administrative Services",
  "Logistics Management",
  "Protective Service Coordination",
  "Travel Coordination",
  "Administrative Services",
  "Senior Leadership Strategies",
  "Protocol Management",
  "Emergency Management, Law Enforcement, and Protective Services",
  "Emergency Management",
  "Criminal Investigation Techniques",
  "Canada – Controlled Goods Program Compliance",
  "Canada – Defence Procurement and Industrial Benefits",
  "Canada – Cybersecurity and Data Protection (PIPEDA)",
  "Canada – Export and Trade Compliance (EIPA)",
  "Canada – Indigenous Business Procurement Strategy",
  "Canada – Government Contracting and Public Services",
  "Canada – National Security and Intelligence Compliance",
  "Canada – Energy Policy and Environmental Regulations",
  "UK – MOD Procurement and Defense Contracts",
  "UK – Cybersecurity and UK GDPR Compliance",
  "UK – Export Controls and Strategic Goods",
  "UK – Intelligence and Security Collaboration",
  "UK – Government Contracting and Public Procurement",
  "UK – Aerospace and Defense Industry Support",
  "UK – Green Energy and Net-Zero Strategy",
  "Australia – Defence Export and Industry Programs",
  "Australia – Cybersecurity and Essential Eight Compliance",
  "Australia – Government Procurement and Contracting (AusTender)",
  "Australia – Export Controls and Defence Trade Act",
  "Australia – Indigenous Business Procurement Policy (IPP)"
]
