export const BusinessIndustries = [
    'Technology',
    'Finance',
    'Healthcare',
    'Education',
    'Retail',
    'Manufacturing',
    'Real Estate',
    'Transportation',
    'Energy',
    'Hospitality',
    'Telecommunications',
    'Agriculture',
    'Construction',
    'Media & Entertainment',
    'Food & Beverage',
    'Legal Services',
    'Logistics & Supply Chain',
    'Aerospace & Defense',
    'Insurance',
    'Nonprofit & NGO',
    'Fashion & Apparel',
    'Beauty & Cosmetics',
    'Automotive',
    'Sports & Recreation',
    'Environmental Services',
    'Government & Public Sector',
    'Human Resources & Staffing',
    'Marketing & Advertising',
    'Consulting',
    'Travel & Tourism',
    'Pharmaceuticals',
    'Biotechnology',
    'Information Services',
    'E-commerce',
    'Cybersecurity',
    'Financial Technology (Fintech)',
    'Green Energy & Sustainability',
    'Publishing',
    'Arts & Design',
    'Home Services',
    'Professional Services',
    'Pet Care & Veterinary',
    'Childcare & Early Education',
    'Event Planning & Services',
    'Security Services',
    'Warehousing & Fulfillment',
    'Waste Management',
    'Mining & Natural Resources',
    'Religious Organizations'
  ];
  