export const GovernmentDepartmentsAndAgenciesByCountry = {
    "United States": [
      "US – Department of Defense (DoD)",
      "US – Department of State (DoS)",
      "US – Department of Homeland Security (DHS)",
      "US – Department of Justice (DOJ)",
      "US – Department of Energy (DOE)",
      "US – Department of Commerce (DOC)",
      "US – Department of the Treasury",
      "US – Department of Health and Human Services (HHS)",
      "US – Department of Transportation (DOT)",
      "US – Department of Veterans Affairs (VA)",
      "US – Department of Agriculture (USDA)",
      "US – Department of the Interior",
      "US – Department of Labor",
      "US – Department of Education",
      "US – Department of Housing and Urban Development (HUD)",
      "US – Environmental Protection Agency (EPA)",
      "US – Federal Bureau of Investigation (FBI)",
      "US – Central Intelligence Agency (CIA)",
      "US – National Security Agency (NSA)",
      "US – Defense Intelligence Agency (DIA)",
      "US – Federal Emergency Management Agency (FEMA)",
      "US – General Services Administration (GSA)",
      "US – National Aeronautics and Space Administration (NASA)",
      "US – Small Business Administration (SBA)",
      "US – Federal Aviation Administration (FAA)",
      "US – US Agency for International Development (USAID)",
      "US – United States Postal Service (USPS)",
      "US – National Institutes of Health (NIH)",
      "US – Centers for Disease Control and Prevention (CDC)",
      "US – Federal Communications Commission (FCC)",
      "US – US Customs and Border Protection (CBP)",
      "US – Immigration and Customs Enforcement (ICE)",
      "US – Transportation Security Administration (TSA)",
      "US – United States Coast Guard",
      "US – United States Secret Service",
      "US – US State and Local Governments",
      "US – National Science Foundation (NSF)",
      "US – National Institute of Standards and Technology (NIST)",
      "US – National Oceanic and Atmospheric Administration (NOAA)",
      "US – United States Geological Survey (USGS)",
      "US – Defense Advanced Research Projects Agency (DARPA)",
      "US – Intelligence Advanced Research Projects Activity (IARPA)",
      "US – Office of Naval Research (ONR)",
      "US – Army Research Laboratory (ARL)",
      "US – Air Force Research Laboratory (AFRL)",
      "US – National Nuclear Security Administration (NNSA)",
      "US – Biomedical Advanced Research and Development Authority (BARDA)",
      "US – National Reconnaissance Office (NRO)",
      "US – Office of Science and Technology Policy (OSTP)",
      "US – US Patent and Trademark Office (USPTO)",
      "US – National Archives and Records Administration (NARA)",
      "US – Office of the Director of National Intelligence (ODNI)",
      "US – Congressional Budget Office (CBO)",
      "US – Government Accountability Office (GAO)",
      "US – Congressional Research Service (CRS)",
      "US – US Senate",
      "US – US House of Representatives",
      "US – House Armed Services Committee (HASC) Staff",
      "US – Senate Armed Services Committee (SASC) Staff",
      "US – House Foreign Affairs Committee (HFAC) Staff",
      "US – Senate Foreign Relations Committee (SFRC) Staff",
      "US – House Appropriations Committee (HAC) Staff",
      "US – Senate Appropriations Committee (SAC) Staff",
      "US – House Intelligence Committee (HPSCI) Staff",
      "US – Senate Intelligence Committee (SSCI) Staff",
      "US – House Oversight and Accountability Committee Staff",
      "US – Senate Homeland Security and Governmental Affairs Committee (HSGAC) Staff",
      "US – Congressional Leadership Offices (Speaker, Majority Leader, Whip, etc.)"
    ],
    "United Kingdom": [
      "UK - Ministry of Defence (MOD)",
      "UK - Foreign, Commonwealth & Development Office (FCDO)",
      "UK - Home Office",
      "UK - Ministry of Justice",
      "UK - Department for Business and Trade",
      "UK - Department for Energy Security and Net Zero",
      "UK - Department of Health and Social Care",
      "UK - HM Treasury",
      "UK - Cabinet Office",
      "UK - Department for Transport",
      "UK - Department for Environment, Food and Rural Affairs",
      "UK - Department for Education",
      "UK - Department for Work and Pensions",
      "UK - Ministry of Housing, Communities and Local Government",
      "UK - Department for Science, Innovation and Technology",
      "UK - Department for Culture, Media and Sport",
      "UK - National Health Service (NHS)",
      "UK - UK Research and Innovation (UKRI)",
      "UK - Security Service (MI5)",
      "UK - Secret Intelligence Service (MI6)",
      "UK - Government Communications Headquarters (GCHQ)",
      "UK - National Crime Agency (NCA)",
      "UK - Environment Agency",
      "UK - UK Space Agency",
      "UK - Civil Aviation Authority (CAA)",
      "UK - Financial Conduct Authority (FCA)",
      "UK - HM Revenue and Customs (HMRC)",
      "UK - Local Authorities and Councils"
    ],
    "Canada": [
      "Canada - Department of National Defence",
      "Canada - Global Affairs Canada",
      "Canada - Public Safety Canada",
      "Canada - Department of Justice",
      "Canada - Innovation, Science and Economic Development Canada",
      "Canada - Natural Resources Canada",
      "Canada - Health Canada",
      "Canada - Finance Canada",
      "Canada - Treasury Board of Canada Secretariat",
      "Canada - Transport Canada",
      "Canada - Environment and Climate Change Canada",
      "Canada - Employment and Social Development Canada",
      "Canada - Immigration, Refugees and Citizenship Canada",
      "Canada - Indigenous Services Canada",
      "Canada - Crown-Indigenous Relations and Northern Affairs",
      "Canada - Agriculture and Agri-Food Canada",
      "Canada - Fisheries and Oceans Canada",
      "Canada - Public Services and Procurement Canada",
      "Canada - Canadian Security Intelligence Service (CSIS)",
      "Canada - Communications Security Establishment (CSE)",
      "Canada - Royal Canadian Mounted Police (RCMP)",
      "Canada - Canada Border Services Agency (CBSA)",
      "Canada - Canadian Space Agency",
      "Canada - Canadian Food Inspection Agency",
      "Canada - Impact Assessment Agency of Canada",
      "Canada - Canadian Transportation Agency",
      "Canada - Canada Revenue Agency (CRA)",
      "Canada - Provincial, Territorial, and Municipal Governments"
    ],
    "Australia": [
      "Australia - Department of Defence",
      "Australia - Department of Foreign Affairs and Trade",
      "Australia - Department of Home Affairs",
      "Australia - Attorney-General's Department",
      "Australia - Department of Industry, Science and Resources",
      "Australia - Department of Climate Change, Energy, the Environment and Water",
      "Australia - Department of Health and Aged Care",
      "Australia - Department of Finance",
      "Australia - Department of the Prime Minister and Cabinet",
      "Australia - Department of Infrastructure, Transport, Regional Development, Communications and the Arts",
      "Australia - Department of Agriculture, Fisheries and Forestry",
      "Australia - Department of Education",
      "Australia - Department of Employment and Workplace Relations",
      "Australia - Department of Social Services",
      "Australia - Australian Security Intelligence Organisation (ASIO)",
      "Australia - Australian Secret Intelligence Service (ASIS)",
      "Australia - Australian Signals Directorate (ASD)",
      "Australia - Australian Federal Police",
      "Australia - Australian Border Force",
      "Australia - Australian Space Agency",
      "Australia - Civil Aviation Safety Authority (CASA)",
      "Australia - Australian Taxation Office (ATO)",
      "Australia - Australian Trade and Investment Commission (Austrade)",
      "Australia - National Disability Insurance Agency (NDIA)",
      "Australia - Commonwealth Scientific and Industrial Research Organisation (CSIRO)",
      "Australia - Australian Research Council",
      "Australia - State, Territory, and Local Governments"
    ]
  };
