export const certificationsList = [
    // custom list
    "GCCI certification",

    // Cloud & DevOps
    "AWS Certified Solutions Architect – Associate",
    "AWS Certified Solutions Architect – Professional",
    "AWS Certified Developer – Associate",
    "AWS Certified SysOps Administrator – Associate",
    "AWS Certified DevOps Engineer – Professional",
    "AWS Certified Cloud Practitioner",
    "Microsoft Certified: Azure Administrator Associate",
    "Microsoft Certified: Azure Developer Associate",
    "Microsoft Certified: Azure Solutions Architect Expert",
    "Microsoft Certified: Azure DevOps Engineer Expert",
    "Google Cloud Professional Cloud Architect",
    "Google Cloud Professional Data Engineer",
    "Google Cloud Professional Cloud Developer",
    "Google Cloud Professional Cloud Network Engineer",
    "Google Cloud Professional Cloud Security Engineer",
    "Google Cloud Associate Cloud Engineer",
    "Certified Kubernetes Administrator (CKA)",
    "Certified Kubernetes Application Developer (CKAD)",
    "Certified Kubernetes Security Specialist (CKS)",
    "Docker Certified Associate (DCA)",
    "Red Hat Certified Engineer (RHCE)",
    "Red Hat Certified Architect (RHCA)",
    "Terraform Associate Certification (HashiCorp)",
  
    // Cybersecurity
    "Certified Information Systems Security Professional (CISSP)",
    "Certified Ethical Hacker (CEH)",
    "CompTIA Security+",
    "CompTIA CySA+ (Cybersecurity Analyst)",
    "CompTIA PenTest+",
    "Certified Information Security Manager (CISM)",
    "Certified Information Systems Auditor (CISA)",
    "Certified Cloud Security Professional (CCSP)",
    "Offensive Security Certified Professional (OSCP)",
    "GIAC Security Essentials (GSEC)",
    "GIAC Certified Incident Handler (GCIH)",
    "GIAC Certified Penetration Tester (GPEN)",
    "Certified Network Defender (CND)",
    "Certified SOC Analyst (CSA)",
    "Certified Web Application Defender (GWEB)",
  
    // Project & IT Management
    "Project Management Professional (PMP)",
    "Certified ScrumMaster (CSM)",
    "Professional Scrum Master (PSM)",
    "SAFe Scrum Master (SSM)",
    "PRINCE2 Foundation/Practitioner",
    "ITIL 4 Foundation",
    "ITIL 4 Specialist/Strategist",
    "Lean Six Sigma (Yellow/Green/Black Belt)",
    "PMI Agile Certified Practitioner (PMI-ACP)",
    "Certified Business Analysis Professional (CBAP)",
  
    // Networking & Systems
    "Cisco Certified Network Associate (CCNA)",
    "Cisco Certified Network Professional (CCNP)",
    "Cisco Certified Internetwork Expert (CCIE)",
    "CompTIA Network+",
    "CompTIA A+",
    "CompTIA Linux+",
    "VMware Certified Professional (VCP)",
    "Microsoft Certified: Windows Server Hybrid Administrator",
  
    // Data & AI
    "AWS Certified Data Analytics – Specialty",
    "Microsoft Certified: Azure Data Scientist Associate",
    "Microsoft Certified: Azure AI Engineer Associate",
    "Google Cloud Professional Machine Learning Engineer",
    "TensorFlow Developer Certificate",
    "Cloudera Certified Data Engineer",
    "Databricks Certified Data Engineer Associate",
    "SAS Certified Data Scientist",
    "Oracle Database SQL Certified Associate",
    "MongoDB Certified Developer",
    "Microsoft Certified: Power BI Data Analyst",
  
    // Programming & Development
    "Oracle Certified Professional: Java SE Programmer",
    "Microsoft Certified: Azure Developer Associate",
    "Microsoft Certified: Power Platform Developer",
    "Google Associate Android Developer",
    "Apple Certified iOS Developer",
    "Salesforce Certified Platform Developer I & II",
    "Salesforce Certified Administrator",
    "HashiCorp Certified: Vault Associate",
    "HashiCorp Certified: Consul Associate",
    "Certified Node.js Developer (OpenJS)",
    "Certified Python Developer (PCAP/PCPP)",
  
    // Blockchain
    "Certified Blockchain Developer (CBD)",
    "Ethereum Certified Developer (ECD)",
    "Hyperledger Fabric Administrator (CHFA)",
  
    // Digital Marketing & SEO
    "Google Analytics Individual Qualification (GAIQ)",
    "Google Ads Certification",
    "HubSpot Content Marketing Certification",
    "Facebook Blueprint Certification",
    "Hootsuite Social Media Certification",
    "SEO Certification (Moz/Udemy/Coursera)",
  
    // Miscellaneous
    "Certified Ethical Hacker (CEH)",
    "Certified Web Professional (CWP)",
    "Certified UX/UI Designer (NN/g, Google UX)",
    "ISTQB Certified Tester (CTFL/CTAL)",
    "Certified Technical Writer (STC/API)",
    "Certified Kubernetes Security Specialist (CKS)",
    "Certified Cloud Native Security Expert (CCNSE)",
  ];