export const australiaDepartments = [
    "Department of Defence",
    "Department of Foreign Affairs and Trade",
    "Department of Home Affairs",
    "Attorney-General's Department",
    "Department of Industry, Science and Resources",
    "Department of Climate Change, Energy, the Environment and Water",
    "Department of Health and Aged Care",
    "Department of Finance",
    "Department of the Prime Minister and Cabinet",
    "Department of Infrastructure, Transport, Regional Development, Communications and the Arts",
    "Department of Agriculture, Fisheries and Forestry",
    "Department of Education",
    "Department of Employment and Workplace Relations",
    "Department of Social Services",
    "Australian Security Intelligence Organisation (ASIO)",
    "Australian Secret Intelligence Service (ASIS)",
    "Australian Signals Directorate (ASD)",
    "Australian Federal Police",
    "Australian Border Force",
    "Australian Space Agency",
    "Civil Aviation Safety Authority (CASA)",
    "Australian Taxation Office (ATO)",
    "Australian Trade and Investment Commission (Austrade)",
    "National Disability Insurance Agency (NDIA)",
    "Commonwealth Scientific and Industrial Research Organisation (CSIRO)",
    "Australian Research Council",
    "State, Territory, and Local Governments"
  ];
  