export const canadaDepartments = [
    "Department of National Defence",
    "Global Affairs Canada",
    "Public Safety Canada",
    "Department of Justice",
    "Innovation, Science and Economic Development Canada",
    "Natural Resources Canada",
    "Health Canada",
    "Finance Canada",
    "Treasury Board of Canada Secretariat",
    "Transport Canada",
    "Environment and Climate Change Canada",
    "Employment and Social Development Canada",
    "Immigration, Refugees and Citizenship Canada",
    "Indigenous Services Canada",
    "Crown-Indigenous Relations and Northern Affairs",
    "Agriculture and Agri-Food Canada",
    "Fisheries and Oceans Canada",
    "Public Services and Procurement Canada",
    "Canadian Security Intelligence Service (CSIS)",
    "Communications Security Establishment (CSE)",
    "Royal Canadian Mounted Police (RCMP)",
    "Canada Border Services Agency (CBSA)",
    "Canadian Space Agency",
    "Canadian Food Inspection Agency",
    "Impact Assessment Agency of Canada",
    "Canadian Transportation Agency",
    "Canada Revenue Agency (CRA)",
    "Provincial, Territorial, and Municipal Governments"
  ];
  