export const ukDepartments = [
    "Ministry of Defence (MOD)",
    "Foreign, Commonwealth & Development Office (FCDO)",
    "Home Office",
    "Ministry of Justice",
    "Department for Business and Trade",
    "Department for Energy Security and Net Zero",
    "Department of Health and Social Care",
    "HM Treasury",
    "Cabinet Office",
    "Department for Transport",
    "Department for Environment, Food and Rural Affairs",
    "Department for Education",
    "Department for Work and Pensions",
    "Ministry of Housing, Communities and Local Government",
    "Department for Science, Innovation and Technology",
    "Department for Culture, Media and Sport",
    "National Health Service (NHS)",
    "UK Research and Innovation (UKRI)",
    "Security Service (MI5)",
    "Secret Intelligence Service (MI6)",
    "Government Communications Headquarters (GCHQ)",
    "National Crime Agency (NCA)",
    "Environment Agency",
    "UK Space Agency",
    "Civil Aviation Authority (CAA)",
    "Financial Conduct Authority (FCA)",
    "HM Revenue and Customs (HMRC)",
    "Local Authorities and Councils"
  ];
  