export const locationList = [
    "Chicago, US",
    "New York, US",
    "Los Angeles, US",
    "San Francisco, US",
    "Seattle, US",
    "Austin, US",
    "Boston, US",
    "Washington, US",
    "Denver, US",
    "Miami, US",
    "Toronto, CA",
    "Vancouver, CA",
    "Montreal, CA",
    "Calgary, CA",
    "Ottawa, CA",
    "London, UK",
    "Manchester, UK",
    "Birmingham, UK",
    "Edinburgh, UK",
]

export const jobCategoryList = [
    "Software Development",
    "Data Science",
    "Product Management",
    "Design",
    "Marketing",
    "Sales",
    "Customer Support",
    "Human Resources",
    "Finance",
    "Operations",
    "Project Management",
    "Business Development",
    "Legal",
    "Content Creation",
    "Quality Assurance",
]

export const requiredSkillsList = [
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "HTML/CSS",
    "React",
    "Angular",
    "Node.js",
    "Django",
    "Flask",
    "SQL",
    "NoSQL",
    "Git",
    "Docker",
    "AWS",
    "Azure",
]

export const requiredCertificationsList = [
    "AWS Certified Solutions Architect",
    "Certified ScrumMaster (CSM)",
    "Project Management Professional (PMP)",
    "Google Cloud Professional Data Engineer",
    "Microsoft Certified: Azure Fundamentals",
    "Cisco Certified Network Associate (CCNA)",
    "CompTIA Security+",
    "Certified Information Systems Security Professional (CISSP)",
    "AWS Certified Developer",
    "Certified Ethical Hacker (CEH)",
]